spring.application.name=bka


###### LOCAL HOST ##########

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/bka_access?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE



###### HOSTING ##########

# spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:49546/railway
# spring.datasource.username=root
# spring.datasource.password=wrVsAbhLchimigcAMRhmmyatBpgAMmCu
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true